### ISSUE TITLE
AlgebraicPetri v0.9

### ISSUE THREAD

**Issue by mehalter** [AlgebraicJulia/AlgebraicPetri.jl#148]
### TODO

- [x] Revert commented out tests after regressions are resolved (#151):
  - [ ] ~~`ModelComparison`: Need to wait until `Subobject` regression is fixed~~
- [x] Update `Project.toml` `[compat]` entries for (#151):
  - [x] `Catlab`
  - [ ] ~~`AlgebraicRewriting`~~
- [x] Make sure tests are passing once Catlab is released
- [x] Change default branch and update branch protection to `main`
- [x] Tag new release v0.9
